### PR TITLE
Support drag and drop events in nested elements

### PR DESCRIPTION
**Pull request by Fweddi**
Co-authored with @twrichards 
______
## What does this change?
Currently Composer's [drop embed plugin](https://github.com/guardian/flexible-content/blob/main/composer/src/js/prosemirror-setup/drop-embed.js#L61) does not work in nested elements (such as Key Takeaways or Q&A). This is because the drag and drop events are swallowed by the inner editor.

This PR builds on the approach @twrichards set out in in #362 and #363 by propagating these events up to the outer editor.

ProseMirror does not have inbuilt support for the drag events in the same way it does for `handleClick` and `handleKeyPress`, so in this PR we have made use of the `handleDOMEvents` property, an object which maps DOM events to handler functions. 

We propagate the events up to be handled by the outer editor, where the drop embed plugin sets its [own handleDOMEvents property](https://github.com/guardian/flexible-content/blob/main/composer/src/js/prosemirror-setup/drop-embed.js#L83-L87) to handle the drag and drop behaviour.

## How to test
Publish locally to Composer using yalc. Drag and drop various Grid links, images and crops into the `content` field of a Key Takeaways / Q&A article. This should trigger the usual drag and drop behaviour.

### CODE REVIEW

**Comment by rhystmills** [comment]
Nice work. That integration test has failed on a few PRs recently - looks like a flaky test and not something you've introduced.

**Comment by Fweddi** [comment]
> Nice work. That integration test has failed on a few PRs recently - looks like a flaky test and not something you've introduced.

Yes - have re-run the tests and they now pass.

**Comment by simonbyford** [comment]
I can't seem to drag media into the content field if it already has text in it:

https://github.com/guardian/prosemirror-elements/assets/7423751/e35f6b8d-5841-4ed3-a632-14963eb7503d

Works fine if it's empty

**Comment by Fweddi** [comment]
> I can't seem to drag media into the content field if it already has text in it:
> 
>  drop.mp4 
> Works fine if it's empty

Interesting, I think in regular content the drop embed will drop before / after a paragraph; here it seems to be dropping on the paragraph itself which might be a cause / effect of the problem? Will investigate further.

**Comment by Fweddi** [comment]
So it turns out we need to pass the drop plugin directly to the list elements (https://github.com/guardian/flexible-content/pull/4743). With this approach we explicitly _don't_ want to bubble drag and drop events up, so I'm closing this PR.

**Pull request closed without merging**
